export const QUESTION_POINTS_MAX = 100;
export const QUESTION_POINTS_MIN = 10;
export const MIN_AMOUNT_OF_CHOICES = 0;
export const MAX_AMOUNT_OF_CHOICES = 4;
export const BONUS_MULTIPLIER = 0.2;
export const OPEN_ENDED_PARTIAL_SCORE = 100;
export const PANIC_ACTIVATION_CUTOFF = 10;
export const PANIC_ACTIVATION_CUTOFF_REVIEWABLE_QUESTION = 20;