// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgApPtCLrdg3dLvPAeu6avZ0ue4NgdUMk',
    appId: '1:791568657647:android:5ec7c748134ec8b064ff1a',
    messagingSenderId: '791568657647',
    projectId: 'kazoo-dd077',
    storageBucket: 'kazoo-dd077.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANxRJE_F-htIz2UuoQjOmVXaGshKshEX8',
    appId: '1:791568657647:web:727daff3d3e24c2e64ff1a',
    messagingSenderId: '791568657647',
    projectId: 'kazoo-dd077',
    authDomain: 'kazoo-dd077.firebaseapp.com',
    storageBucket: 'kazoo-dd077.firebasestorage.app',
    measurementId: 'G-DNVSFB4X1G',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANxRJE_F-htIz2UuoQjOmVXaGshKshEX8',
    appId: '1:791568657647:web:727daff3d3e24c2e64ff1a',
    messagingSenderId: '791568657647',
    projectId: 'kazoo-dd077',
    authDomain: 'kazoo-dd077.firebaseapp.com',
    storageBucket: 'kazoo-dd077.firebasestorage.app',
    measurementId: 'G-DNVSFB4X1G',
  );

}